WIP: Feature/game2
AlexeyMachehin/Bomberman pull request #38
Opened 2023-02-07 20:01 UTC by dmitmokrov

Игра на страничке /game2

2023-02-26 15:05 UTC, AlexeyMachehin requested changes
Нашел некоторые баги, думаю их стоит устранить в первую очередь:
1. При нажатии двух стрелок одновременно (например вниз и вправо) персонаж ходит по диагонали и проходит сквозь непроходимую стену.
2. Пока нет уровней, настроить постоянное количество врагов при старте игры. Сейчас количество вычисляется рандомно и бывает что враг на карте появляется один, а бывает что их слишком много.
3. Иногда сразу после старта игры враг оказывается вплотную к персонажу и игра заканчивается проигрышем.
4. Добавить анимацию после смерти персонажа и врага.(можно сделать позднее)

2023-02-26 15:05 UTC, AlexeyMachehin commented on packages/client/src/features/GameEngine2/Enemy.ts
> +            }
Предлагаю сделать короче и создать переменные

```
for (let column = 0; column < cells[0].length; column++) {
        const mapElementY = row * this.cellSize;
        const mapElementX = column * this.cellSize;
        const nextStepEnemyX = this.x + this.cellSize;
        const nextStepEnemyY = this.y + this.cellSize;
        // condition1, condition2 - изменить название на подходящее или добавить комментарий
        const condition1 = (column + 1) * this.cellSize;
        const condition2 = (row + 1) * this.cellSize;
        switch (cells[row][column]) {
          case MapElement.wall:
          case MapElement.softWall:
          case MapElement.bomb:
            if (this.y === mapElementY) {
              if (this.x === condition1 || nextStepEnemyX === mapElementX) {
                count++;
              }
            }
            if (this.x === mapElementX) {
              if (this.y === condition2 || nextStepEnemyY === mapElementY) {
                count++;
              }
            }
        }
      }
```

2023-02-26 15:05 UTC, AlexeyMachehin commented on packages/client/src/features/GameEngine2/Enemy.ts
> +      }
Тоже самое
```
for (let column = 0; column < cells[0].length; column++) {
        const newAxios = Math.random() < 0.5 ? 'x' : 'y';
        const newDirection = Math.random() < 0.5 ? -1 : 1;
        const mapElementY = row * this.cellSize;
        const mapElementX = column * this.cellSize;
        // smth1, smth2 - изменить название на подходящее или добавить комментарий
        const smth1 = (column + 1) * this.cellSize;
        const smth2 = (row + 1) * this.cellSize;
        switch (cells[row][column]) {
          case MapElement.wall:
          case MapElement.softWall:
          case MapElement.bomb:
            if (this.axis === 'x' && this.y === mapElementY) {
              // condition1, condition2 - изменить название на подходящее или добавить комментарий
              const condition1 = this.direction === -1 && this.x === smth1;
              const condition2 = this.direction === 1 && this.x + this.cellSize === mapElementX;
              if (condition1 || condition2) {
                this.axis = newAxios;
                this.direction = newDirection;
                return;
              }
            } else if (this.axis === 'y' && this.x === mapElementX) {
              // condition3, condition4 - изменить название на подходящее или добавить комментарий
              const condition3 = this.direction === -1 && this.y === smth2;
              const condition4 = this.direction === 1 && this.y + this.cellSize === mapElementY;
              if (condition3 || condition4) {
                this.axis = newAxios;
                this.direction = newDirection;
                return;
              }
            }
```

2023-02-26 15:05 UTC, AlexeyMachehin commented on packages/client/src/features/GameEngine2/Enemy.ts
> +  }
Возможно второе условие лишнее, мы можем подредактировать верхнее условие
```
 if (
      ((player.x + this.cellSize > this.x && player.x <= this.x) ||
        (player.x < this.x + this.cellSize && player.x >= this.x)) &&
      ((player.y >= this.y && player.y < this.y + this.cellSize) ||
        (player.y <= this.y && player.y + this.cellSize > this.y))
    ) {
      return true;
    }
```

2023-02-26 15:05 UTC, AlexeyMachehin commented on packages/client/src/features/GameEngine2/Player.ts
> +  }
Предлагаю повторяющиеся условия вынести в переменные и добавить описание в виде комментария

2023-03-05 19:46 UTC, g0liaeth approved these changes

2023-03-13 19:26 UTC, AlexeyMachehin approved these changes

2023-03-16 14:22 UTC, iapolya reviewed
Это было не страшно 😅

2023-03-16 14:22 UTC, iapolya commented on packages/client/src/const.ts
> +export const RESOURCE_URL = 'https://ya-praktikum.tech/api/v2/resources';
Переименовала бы файл на config или что-то подобное

2023-03-16 14:22 UTC, iapolya commented on packages/client/src/features/GameEngine2/Enemy.ts
> +  move(cells: any) {
Почему нет конкретной типизации?

2023-03-16 14:22 UTC, iapolya commented on packages/client/src/features/GameEngine2/Enemy.ts
> +  }
Да, словно только второе и нужно оставить. А вообще что должна возвращать функция? Добавьте тип. Скорее всего значение false тоже должно возвращаться и как-то обрабатываться. В таком случае, можно еще больше упростить всё

2023-03-16 14:22 UTC, iapolya commented on packages/client/src/features/GameEngine2/Player.ts
> +        ((this.y >= row * this.cellSize &&
45-48, 52-55 повторяются (вроде бы)
Стоит упростить выражения, вынеся это в константу или еще как-нибудь + пройдись по остальному коду и попробуй сделать то же самое. Это сделает код более читаемым и упростит возможный дебаг

2023-03-16 14:22 UTC, iapolya commented on packages/client/src/features/GameEngine2/Player.ts
> +        ((this.x >= column * this.cellSize &&
И здесь

2023-03-18 09:03 UTC, dmitmokrov commented on packages/client/src/features/GameEngine2/Enemy.ts
> +  }
Условия верные. False можно явно вернуть (поправлю, но это не повлияет ни на что), т.к. неявно возвращается undefined. Условия нужны оба, потому что в первом условии проверяется пересечение игрока и врага по x координате, при этом у координата может быть равна в крайнем случае. А во втором условии проверяется пересечение по y координате, при этом x координата может быть равна.

2023-03-18 09:05 UTC, dmitmokrov commented on packages/client/src/features/GameEngine2/Enemy.ts
> +  move(cells: any) {
поправил

2023-03-18 15:23 UTC, g0liaeth approved these changes

2023-03-18 16:59 UTC, AlexeyMachehin approved these changes

2023-03-18 17:10 UTC, merged