Добавляет страницы профиля и его редактирования + все апи
AlexeyMachehin/Bomberman pull request #41
Opened 2023-03-05 10:11 UTC by dmitmokrov

- Добавляет страницы профиля, его редактирования, редактирования пароля
- Добавляет валидацию всем формам
- Добавляет соответствующие апи

2023-03-05 14:48 UTC, AlexeyMachehin requested changes

2023-03-05 14:48 UTC, AlexeyMachehin commented on packages/client/src/pages/profile/Profile.tsx
> +const user = {
Так как подключен Redux и user есть в стейте, давай возьмем его оттуда

2023-03-05 14:48 UTC, AlexeyMachehin commented on packages/client/src/pages/profileChange/ProfileChange.tsx
> +const ProfileChange = () => {
Давай будем выводить предыдущие данные юзера в инпутах

2023-03-05 20:12 UTC, g0liaeth approved these changes

2023-03-11 16:33 UTC, dmitmokrov commented on packages/client/src/pages/profile/Profile.tsx
> +const user = {
Поправил

2023-03-11 16:33 UTC, dmitmokrov commented on packages/client/src/pages/profileChange/ProfileChange.tsx
> +const ProfileChange = () => {
Поправил

2023-03-11 16:54 UTC, AlexeyMachehin approved these changes

2023-03-13 07:04 UTC, iapolya approved these changes

2023-03-13 07:04 UTC, iapolya commented on packages/client/src/features/profileChange/hooks/useProfileChangeFormik.ts
> +export interface IProfileChangeFormValues {
В чем разница IProfileChangeFormValues и IFormValue?

2023-03-13 07:04 UTC, iapolya commented on packages/client/src/pages/passwordChange/PasswordChange.tsx
> +      .then(() => dispatch(getUser()))
Добавила бы еще блок catch для обработки возможных ошибок

2023-03-15 19:46 UTC, AlexeyMachehin approved these changes

2023-03-15 19:47 UTC, merged